/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anslab5;

import anslab1.AnsLab1;
import anslab2.AnsLab2;
import anslab3.AnsLab3;
import anslab4.AnsLab4;

/**
 *
 * @author El Gato
 */
public class AnsLab5 extends javax.swing.JFrame {
    
    private final AnsLab1 anslab1;
    private final AnsLab2 anslab2;
    private final AnsLab3 anslab3;
    private final AnsLab4 anslab4;

    /**
     * Creates new form Menu
     */
    public AnsLab5() {
        anslab1 = new AnsLab1();
        anslab2 = new AnsLab2();
        anslab3 = new AnsLab3();
        anslab4 = new AnsLab4();
                
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AnsLab1 = new javax.swing.JButton();
        AnsLab2 = new javax.swing.JButton();
        AnsLab3 = new javax.swing.JButton();
        AnsLab4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescriptionArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        AnsLab1.setText("AnsLab1");
        AnsLab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AnsLab1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AnsLab1MouseExited(evt);
            }
        });
        AnsLab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsLab1ActionPerformed(evt);
            }
        });

        AnsLab2.setText("AnsLab2");
        AnsLab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AnsLab2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AnsLab2MouseExited(evt);
            }
        });
        AnsLab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsLab2ActionPerformed(evt);
            }
        });

        AnsLab3.setText("AnsLab3");
        AnsLab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AnsLab3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AnsLab3MouseExited(evt);
            }
        });
        AnsLab3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsLab3ActionPerformed(evt);
            }
        });

        AnsLab4.setText("AnsLab4");
        AnsLab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AnsLab4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AnsLab4MouseExited(evt);
            }
        });
        AnsLab4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsLab4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("3SC Mini Package");

        jLabel2.setText("a main menu system that  calls the different application ");

        jLabel3.setText("programs developed in the previous  exercises");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        DescriptionArea.setEditable(false);
        DescriptionArea.setColumns(20);
        DescriptionArea.setRows(5);
        jScrollPane1.setViewportView(DescriptionArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(AnsLab1)
                        .addGap(51, 51, 51)
                        .addComponent(AnsLab2)
                        .addGap(50, 50, 50)
                        .addComponent(AnsLab3)
                        .addGap(51, 51, 51)
                        .addComponent(AnsLab4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnsLab4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnsLab3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnsLab2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnsLab1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnsLab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsLab1ActionPerformed
        // TODO add your handling code here:
        anslab1.setVisible(true);
    }//GEN-LAST:event_AnsLab1ActionPerformed

    private void AnsLab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsLab2ActionPerformed
        // TODO add your handling code here:
        anslab2.setVisible(true);
        
        
    }//GEN-LAST:event_AnsLab2ActionPerformed

    private void AnsLab3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsLab3ActionPerformed
        // TODO add your handling code here:
        anslab3.setVisible(true);
    }//GEN-LAST:event_AnsLab3ActionPerformed

    private void AnsLab4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsLab4ActionPerformed
        // TODO add your handling code here:
        anslab4.setVisible(true);
    }//GEN-LAST:event_AnsLab4ActionPerformed

    private void AnsLab1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnsLab1MouseEntered
        String AnsLab1_Description = "{Samples Generator} \n" +
                "simulates the Simple Random Sampling\n" +
               "and Systematic Sampling Procedures\n" +
                 "in getting a sample from the target population.";
        
        DescriptionArea.setText(AnsLab1_Description);
    }//GEN-LAST:event_AnsLab1MouseEntered

    private void AnsLab1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnsLab1MouseExited
        // TODO add your handling code here:
        clearDescriptionArea();
    }//GEN-LAST:event_AnsLab1MouseExited

    private void AnsLab2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnsLab2MouseEntered
         String AnsLab2_Description = "{Frequency Distribution Calculator} \n" +
                "automates the construction\n" +
               "of the FDT or RFT as well as the generation\n" +
                 "of the corresponding bar chart.";
        
        DescriptionArea.setText(AnsLab2_Description);
    }//GEN-LAST:event_AnsLab2MouseEntered

    private void AnsLab2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnsLab2MouseExited
        // TODO add your handling code here:
        clearDescriptionArea();
    }//GEN-LAST:event_AnsLab2MouseExited

    private void AnsLab3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnsLab3MouseEntered
            String AnsLab3_Description = "{Stem and Leaf Plot} \n" +
                "automates the construction of a stem-and-leaf\n" +
               "plot with a feature that allows annotation \n" +
                 "for the interpretation of the output.";
        
        DescriptionArea.setText(AnsLab3_Description);
    }//GEN-LAST:event_AnsLab3MouseEntered

    private void AnsLab3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnsLab3MouseExited
        // TODO add your handling code here:
        clearDescriptionArea();
    }//GEN-LAST:event_AnsLab3MouseExited

    private void AnsLab4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnsLab4MouseEntered
         String AnsLab4_Description = "{Measures of Central Tendency Calculator} \n" +
                "automates the computation for the measures of \n" +
               "central tendency (mean, median, and mode) and the \n" +
                 "corresponding measures of dispersion (variance-standard \n" +
                 "deviation, Inter-quartile Deviation, and Range) with a  \n" +
                 "feature that allows annotation for the interpretation of \n" +
                 "the output.";
        
        DescriptionArea.setText(AnsLab4_Description);
    }//GEN-LAST:event_AnsLab4MouseEntered

    private void AnsLab4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnsLab4MouseExited
        // TODO add your handling code here:
        clearDescriptionArea();
    }//GEN-LAST:event_AnsLab4MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnsLab5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnsLab5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnsLab5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnsLab5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnsLab5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnsLab1;
    private javax.swing.JButton AnsLab2;
    private javax.swing.JButton AnsLab3;
    private javax.swing.JButton AnsLab4;
    private javax.swing.JTextArea DescriptionArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    private void clearDescriptionArea(){
        DescriptionArea.setText(null);
    }

}
