/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anslab3;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author El Gato
 */
public class DoublePlot extends javax.swing.JPanel {

    /**
     * Creates new form DoublePlot
     */
    
        
    private static double leafUnit;
    private static double stemUnit;
    private static int hStem1;
    private static int hStem2;
    private static int set1Size;
    private static int set2Size;
    private static String label1;
    private static String label2;
    private static ArrayList<String> theOutPut;
    private static outPut OutPutView;
    private static int dataSets;
    private static StemAndLeafGenerator salg;
    
    private static LinkedList<Double> location1;
    private static LinkedList<Double> location2;
    private static LinkedList<Double> inputs;
    private Double leaf, stem;
    
    
    String description = "";
    boolean flag;
    String datainput = "";
    
    
    
    
    
    public DoublePlot() {
        salg = new StemAndLeafGenerator();
        initComponents();
        
        theOutPut = new ArrayList<String>();
       
        LinkedList<Double> location1 = new LinkedList<Double>();
        LinkedList<Double> location2 = new LinkedList<Double>();
        LinkedList<Double> inputs = new LinkedList<Double>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        GeneratePlotButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        LabelRightSideField = new javax.swing.JTextField();
        LabelRightSideButton = new javax.swing.JButton();
        SetRightValuesField = new javax.swing.JTextField();
        SetRightValuesButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ValuesSet = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Size = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        LabelLeftSideField = new javax.swing.JTextField();
        LabelLeftSideButton = new javax.swing.JButton();
        SetLeftValuesField = new javax.swing.JTextField();
        SetLeftValuesButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        LeftValuesSet = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        LeftSize = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SetLeafUnitField2 = new javax.swing.JTextField();
        SetStemUnitField2 = new javax.swing.JTextField();
        SetLeafUnitButton2 = new javax.swing.JButton();
        SetStemUnitButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setText("Double Plot");

        GeneratePlotButton.setText("Generate Plot");
        GeneratePlotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneratePlotButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Label (Right Side):");

        LabelRightSideButton.setText("Set Label");
        LabelRightSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabelRightSideButtonActionPerformed(evt);
            }
        });

        SetRightValuesButton.setText("Set Values");
        SetRightValuesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetRightValuesButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Values:");

        ValuesSet.setText(" ");

        jLabel13.setText("Size:");

        Size.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(Size, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ValuesSet, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SetRightValuesField, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SetRightValuesButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelRightSideField, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelRightSideButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LabelRightSideField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelRightSideButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SetRightValuesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SetRightValuesButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ValuesSet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Size))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel6.setText("Label (Left Side):");

        LabelLeftSideButton.setText("Set Label");
        LabelLeftSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabelLeftSideButtonActionPerformed(evt);
            }
        });

        SetLeftValuesButton.setText("Set Values");
        SetLeftValuesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetLeftValuesButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Values:");

        LeftValuesSet.setText(" ");

        jLabel14.setText("Size:");

        LeftSize.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(LeftSize, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(LeftValuesSet, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(SetLeftValuesField, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SetLeftValuesButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelLeftSideField, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelLeftSideButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(LabelLeftSideField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelLeftSideButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SetLeftValuesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SetLeftValuesButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(LeftValuesSet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(LeftSize))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel8.setText("Set Leaf Unit:");

        jLabel9.setText("Set Stem Unit:");

        SetLeafUnitButton2.setText("Set");
        SetLeafUnitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetLeafUnitButton2ActionPerformed(evt);
            }
        });

        SetStemUnitButton2.setText("Set");
        SetStemUnitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetStemUnitButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SetStemUnitField2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(SetLeafUnitField2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SetLeafUnitButton2)
                    .addComponent(SetStemUnitButton2))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(SetLeafUnitField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SetLeafUnitButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(SetStemUnitField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SetStemUnitButton2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GeneratePlotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)))))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(GeneratePlotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GeneratePlotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneratePlotButtonActionPerformed
        // TODO add your handling code here:
        salg.setLabel1(label1);
        salg.setLabel2(label2);
        //salg.setOutPutView(new outPut()));
        salg.setLeafUnit(leaf);
        salg.setStemUnit(stem);
        
        
        hStem1 = salg.getHigestStem(location1);
        Map<Integer, List<Integer>> plot1 = salg.createPlot(location1);
        salg.setSet1Size(location1.size());
        
        
        hStem2 = salg.getHigestStem(location2);
        Map<Integer, List<Integer>> plot2 = salg.createPlot(location2);
        salg.setSet2Size(location2.size());
        
        salg.printParallelPlot(plot2, plot1);
        
        
    }//GEN-LAST:event_GeneratePlotButtonActionPerformed

    private void LabelRightSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabelRightSideButtonActionPerformed
        // TODO add your handling code here:
        label1 = LabelRightSideField.getText();
        LabelRightSideButton.setEnabled(false);
        LabelRightSideField.setEnabled(false);
    }//GEN-LAST:event_LabelRightSideButtonActionPerformed

    private void SetRightValuesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetRightValuesButtonActionPerformed
        // TODO add your handling code here:
        datainput = SetRightValuesField.getText();
        inputs = salg.convertToArray(datainput);
        location1 = new LinkedList<Double>(inputs);
        Collections.sort(location1);

        ValuesSet.setText(Arrays.toString(location1.toArray()));
        Size.setText(String.valueOf(location1.size()));

        SetRightValuesButton.setEnabled(false);
        SetRightValuesField.setEnabled(false);

        inputs.clear();
    }//GEN-LAST:event_SetRightValuesButtonActionPerformed

    private void LabelLeftSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabelLeftSideButtonActionPerformed
        // TODO add your handling code here:
        label2 = LabelLeftSideField.getText();
        LabelLeftSideButton.setEnabled(false);
        LabelLeftSideField.setEnabled(false);
    }//GEN-LAST:event_LabelLeftSideButtonActionPerformed

    private void SetLeftValuesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetLeftValuesButtonActionPerformed
        // TODO add your handling code here:
        datainput = SetLeftValuesField.getText();
        inputs = salg.convertToArray(datainput);
        location2 = new LinkedList<Double>(inputs);
        Collections.sort(location2);

        LeftValuesSet.setText(Arrays.toString(location2.toArray()));
        LeftSize.setText(String.valueOf(location2.size()));

        SetLeftValuesButton.setEnabled(false);
        SetLeftValuesField.setEnabled(false);

        inputs.clear();
    }//GEN-LAST:event_SetLeftValuesButtonActionPerformed

    private void SetLeafUnitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetLeafUnitButton2ActionPerformed
        // TODO add your handling code here:
        leaf = Double.valueOf(SetLeafUnitField2.getText());
        SetLeafUnitButton2.setEnabled(false);
        SetLeafUnitField2.setEnabled(false);
    }//GEN-LAST:event_SetLeafUnitButton2ActionPerformed

    private void SetStemUnitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetStemUnitButton2ActionPerformed
        // TODO add your handling code here:
        stem = Double.valueOf(SetStemUnitField2.getText());
        if(stem.compareTo(leaf)==1){
            SetStemUnitButton2.setEnabled(false);
            SetStemUnitField2.setEnabled(false);
        }
        else{
            stem = null;
            JOptionPane.showMessageDialog(null, "Stem should be greater than the leaf");
        }
    }//GEN-LAST:event_SetStemUnitButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GeneratePlotButton;
    private javax.swing.JButton LabelLeftSideButton;
    private javax.swing.JTextField LabelLeftSideField;
    private javax.swing.JButton LabelRightSideButton;
    private javax.swing.JTextField LabelRightSideField;
    private javax.swing.JLabel LeftSize;
    private javax.swing.JLabel LeftValuesSet;
    private javax.swing.JButton SetLeafUnitButton2;
    private javax.swing.JTextField SetLeafUnitField2;
    private javax.swing.JButton SetLeftValuesButton;
    private javax.swing.JTextField SetLeftValuesField;
    private javax.swing.JButton SetRightValuesButton;
    private javax.swing.JTextField SetRightValuesField;
    private javax.swing.JButton SetStemUnitButton2;
    private javax.swing.JTextField SetStemUnitField2;
    private javax.swing.JLabel Size;
    private javax.swing.JLabel ValuesSet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
