/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anslab3;

import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import static anslab3.StemAndLeafGenerator.*;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Scanner;

/**
 *
 * @author El Gato
 */
public class SinglePlot extends javax.swing.JPanel {

    /**
     * Creates new form SinglePlot
     */
    
    private static double leafUnit;
    private static double stemUnit;
    private static int hStem1;
    private static int hStem2;
    private static int set1Size;
    private static int set2Size;
    private static String label1;
    private static String label2;
    private static ArrayList<String> theOutPut;
    private static outPut OutPutView;
    private static int dataSets;
    private static StemAndLeafGenerator salg;
    
    private static LinkedList<Double> location1;
    private static LinkedList<Double> location2;
    private static LinkedList<Double> inputs;
    private Double leaf, stem;
    
    
    String description = "";
    boolean flag;
    String datainput = "";
    

    public SinglePlot() {
        salg = new StemAndLeafGenerator();
        initComponents();
        
        theOutPut = new ArrayList<String>();
       
        LinkedList<Double> location1 = new LinkedList<Double>();
        LinkedList<Double> location2 = new LinkedList<Double>();
        LinkedList<Double> inputs = new LinkedList<Double>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        LabelRightSideField = new javax.swing.JTextField();
        LabelRightSideButton = new javax.swing.JButton();
        SetRightValuesField = new javax.swing.JTextField();
        SetRightValuesButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ValuesSet = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Size = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SetLeafUnitField2 = new javax.swing.JTextField();
        SetStemUnitField2 = new javax.swing.JTextField();
        SetLeafUnitButton2 = new javax.swing.JButton();
        SetStemUnitButton2 = new javax.swing.JButton();
        GeneratePlotButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 255));

        jLabel3.setText("Label (Right Side):");

        LabelRightSideButton.setText("Set Label");
        LabelRightSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabelRightSideButtonActionPerformed(evt);
            }
        });

        SetRightValuesButton.setText("Set Values");
        SetRightValuesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetRightValuesButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Values:");

        ValuesSet.setText(" ");

        jLabel4.setText("Size:");

        Size.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(Size, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(ValuesSet, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SetRightValuesField, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SetRightValuesButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelRightSideField, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelRightSideButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LabelRightSideField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelRightSideButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SetRightValuesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SetRightValuesButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ValuesSet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Size))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel8.setText("Set Leaf Unit:");

        jLabel9.setText("Set Stem Unit:");

        SetLeafUnitButton2.setText("Set");
        SetLeafUnitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetLeafUnitButton2ActionPerformed(evt);
            }
        });

        SetStemUnitButton2.setText("Set");
        SetStemUnitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetStemUnitButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SetStemUnitField2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(SetLeafUnitField2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SetLeafUnitButton2)
                    .addComponent(SetStemUnitButton2))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(SetLeafUnitField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SetLeafUnitButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(SetStemUnitField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SetStemUnitButton2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        GeneratePlotButton.setText("Generate Plot");
        GeneratePlotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneratePlotButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Single Plot");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 594, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(GeneratePlotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))))
            .addGroup(layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(GeneratePlotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LabelRightSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabelRightSideButtonActionPerformed
        // TODO add your handling code here:
        label1 = LabelRightSideField.getText();
        LabelRightSideButton.setEnabled(false);
        LabelRightSideField.setEnabled(false);
    }//GEN-LAST:event_LabelRightSideButtonActionPerformed

    private void SetRightValuesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetRightValuesButtonActionPerformed
        // TODO add your handling code here:
        datainput = SetRightValuesField.getText();
        inputs = salg.convertToArray(datainput);
        location1 = new LinkedList<Double>(inputs);
        Collections.sort(location1);
        
        ValuesSet.setText(Arrays.toString(location1.toArray()));
        Size.setText(String.valueOf(location1.size()));
        
        SetRightValuesButton.setEnabled(false);
        SetRightValuesField.setEnabled(false);
        
        
        inputs.clear();
    }//GEN-LAST:event_SetRightValuesButtonActionPerformed

    private void SetLeafUnitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetLeafUnitButton2ActionPerformed
        // TODO add your handling code here:
        leaf = Double.valueOf(SetLeafUnitField2.getText());
        SetLeafUnitButton2.setEnabled(false);
        SetLeafUnitField2.setEnabled(false);
    }//GEN-LAST:event_SetLeafUnitButton2ActionPerformed

    private void SetStemUnitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetStemUnitButton2ActionPerformed
        // TODO add your handling code here:
        stem = Double.valueOf(SetStemUnitField2.getText());
        if(stem.compareTo(leaf)==1){
            SetStemUnitButton2.setEnabled(false);
            SetStemUnitField2.setEnabled(false);
        }
        else{
            stem = null;
            JOptionPane.showMessageDialog(null, "Stem should be greater than the leaf");
        }
    }//GEN-LAST:event_SetStemUnitButton2ActionPerformed

    private void GeneratePlotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneratePlotButtonActionPerformed
        // TODO add your handling code here:
        salg.setLabel1(label1);
        //salg.setOutPutView(new outPut()));
        salg.setLeafUnit(leaf);
        salg.setStemUnit(stem);
        
        
        hStem1 = salg.getHigestStem(location1);
        Map<Integer, List<Integer>> plot1 = salg.createPlot(location1);
        salg.setSet1Size(location1.size());
        salg.printSinglePlot(plot1);
        
        //salg.printSinglePlot(salg.createPlot(inputs));
    }//GEN-LAST:event_GeneratePlotButtonActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GeneratePlotButton;
    private javax.swing.JButton LabelRightSideButton;
    private javax.swing.JTextField LabelRightSideField;
    private javax.swing.JButton SetLeafUnitButton2;
    private javax.swing.JTextField SetLeafUnitField2;
    private javax.swing.JButton SetRightValuesButton;
    private javax.swing.JTextField SetRightValuesField;
    private javax.swing.JButton SetStemUnitButton2;
    private javax.swing.JTextField SetStemUnitField2;
    private javax.swing.JLabel Size;
    private javax.swing.JLabel ValuesSet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
